### ISSUE TITLE
ERROR 'map_csv is a file when evaluate the results' using my_eval.sh

### ISSUE THREAD

**Issue by zxcvbml** [YanFangCS/AINET#5]
when I  evaluate my output, I got a error as follows, I revise it  by [README.md](https://github.com/YanFangCS/AINET#readme), Idon't know the reason.  hoping your response.  thank you very much.
```
ruby@ruby-MS-7D36:~/code/superpixel-benchmark/examples$ bash bash/my_eval.sh 
54
bash/my_eval.sh: 行 43: /home/ruby/code/AINET/output/test_multiscale_enforce_connect/SPixelNet_nSpixel_54/map_csv: 是一个目录
```

the settings in the my_eval.sh as follows:

SUPERPIXELS=("54" "96" "150" "216" "294" "384" "486" "600" "726" "864" "1014" "1176" "1350" "1536" "1944") #

#SUPERPIXELS=("293" "1175") #
IMG_PATH=/home/ruby/code/AINET/test
GT_PATH=/home/ruby/code/AINET/test/map_csv

for SUPERPIXEL in "${SUPERPIXELS[@]}"
do
   echo $SUPERPIXEL
        /home/ruby/code/AINET/output/test_multiscale_enforce_connect/SPixelNet_nSpixel_${SUPERPIXEL}/map_csv $IMG_PATH $GT_PATH  

done

**Comment by wangyxxjtu** [comment]
hi, I never ran into this error, did you run the test code of the superpixel benchmark?

**Comment by zxcvbml** [comment]
> 
May I ask which test code you are referring to？I just build it except matlab and java.
the path of AINet is /home/ruby/code/AINet
and the path of superpixel benchmark is /home/ruby/code/superpixel_benchmark

**Comment by zxcvbml** [comment]
Hi, I revise my_eval.sh as follows.

```
SUPERPIXELS=("54" "96" "150" "216" "294" "384" "486" "600" "726" "864" "1014" "1176" "1350" "1536" "1944") #

# SUPERPIXELS=("293" "1175") #
IMG_PATH=/home/ruby/code/AINET/test
GT_PATH=/home/ruby/code/AINET/test/map_csv

for SUPERPIXEL in "${SUPERPIXELS[@]}"
do
   echo $SUPERPIXEL
        /home/ruby/code/AINET/output_woAI/test_multiscale_enforce_connect/SPixelNet_nSpixel_${SUPERPIXEL}/map_csv  $IMG_PATH $GT_PATH  

done
```
the print:
> 54 /home/ruby/code/AINET/output_woAI/test_multiscale_enforce_connect/SPixelNet_nSpixel_54/map_csv /home/ruby/code/AINET/test /home/ruby/code/AINET/test/map_csv

It seems that no execute code in my_eval.sh.
Hoping your help. Thank you

**Comment by zxcvbml** [comment]
Thank you . I  have addresed it.
